# -*- coding: utf-8 -*-
"""MANGO population coding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VX_AiB5eGtMKXaLE_XDw5rma2Xb6emlt

#Imports
"""

!pip install scipy --upgrade --quiet
!pip install GitPython --quiet
!pip install wget --quiet

!pip install driada

import shutil
import importlib
import git
import sys
import json
import yaml
import pandas as pd
import seaborn as sns

import os
import tqdm
import hashlib
import copy

from itertools import combinations
import numpy as np

from functools import partialmethod
import matplotlib.pyplot as plt
import pickle
import warnings
import pandas as pd
from os.path import join

from driada.gdrive.download import download_part_of_folder
from driada.gdrive.upload import save_file_to_gdrive

from driada.utils.output import *

"""#Loading"""

from google.colab import drive
drive.mount('/gdrive', force_remount=True)
NET = 'SJ-SNN-50'
PATH = f'/gdrive/MyDrive/iNeuroLab/MANGO (neurotrain)/Activity'


#LAYERS = ['sn1', 'layer1.0.sn2', 'layer1.1.sn2', 'layer2.0.sn2', 'layer2.1.sn2',
#          'layer3.0.sn2', 'layer3.1.sn2', 'layer4.0.sn2', 'layer4.1.sn2', 'fc']
LAYERS = ['sn1', 'layer1.0.sn1', 'layer1.0.sn2',
          'layer1.1.sn1', 'layer1.1.sn2',
          'layer2.0.sn1', 'layer2.0.sn2',
          'layer2.1.sn1', 'layer2.1.sn2',
          'layer3.0.sn1', 'layer3.0.sn2',
          'layer3.1.sn1', 'layer3.1.sn2',
          'layer4.0.sn1', 'layer4.0.sn2',
          'layer4.1.sn1', 'layer4.1.sn2']

ITERS = [0,5,10,20,30,40,50,60,70,80,90,100,150,200,250,300,400,500,600,700]

label_names = {
    0: 'airplane',
    1: 'automobile',
    2: 'bird',
    3: 'cat',
    4: 'deer',
    5: 'dog',
    6: 'frog',
    7: 'horse',
    8: 'ship',
    9: 'truck',
}

iter = 50
part = 'test'
layer = 'layer1.1.sn2'

def get_act_data(iter, part, layer):
    path = join(PATH, NET, f'iter {iter}', part)
    name = f'SJ-SNN act iter {iter} {part} layer {layer}.npy.npz'
    with np.load(join(path, name), name) as data:
        act = data['arr_0']

    return act

act = get_act_data(iter, part, layer)
lname = f'CIFAR {part} labels.npz'
labels = np.load(join(PATH, lname))['arr_0']

"""#Dim reduction"""

from driada.dim_reduction.data import *
from driada.dim_reduction.dr_base import *
from driada.dim_reduction.embedding import *
from driada.dim_reduction.graph import *
from driada.intense.visual import *

metric_params = {
    'metric_name' : 'l2',
    'sigma' : 1,
    'p' : 2
}

graph_params = {
    'g_method_name' : 'knn',
    'weighted': 0,
    'nn' : 20,
    'max_deleted_nodes' : 0.2,
    'dist_to_aff': 'hk'
}

embedding_params = {
    'e_method_name' : 'umap',
    'check_graph_connectivity': 0,
    'min_dist': 0.4,
    'dm_alpha': 0.0,
    'dim' : 10
}

mname = embedding_params['e_method_name']
embedding_params['e_method'] = METHODS_DICT[mname]

ds=1
data = act.mean(axis=0).T
#data += np.random.normal(size = data.shape)*1e-9
D = MVData(data[:,:], rescale_rows=True, downsampling=ds)

emb = D.get_embedding(embedding_params, g_params=graph_params, m_params=metric_params)
coords = emb.coords

emethod = embedding_params['e_method_name']

def get_latent_image(coords, title=None):
    fig = plt.figure(figsize=(12,12), dpi=300)
    fig.set_tight_layout(True)
    ax = fig.add_subplot(111, projection='3d')

    cmap = 'plasma'
    colordata = labels/10.0

    ax = make_beautiful(ax)
    fig.suptitle(title, fontsize=30)

    clrs = ['r', 'g', 'b', 'c', 'violet', 'y', 'k', 'gold', 'purple', 'brown']
    #ax.set_title(f'color = {colordataname}', fontsize=14)
    for lb in range(10):
        lb_inds = np.where(labels == lb)[0]
        ax.scatter(coords[0][lb_inds], coords[1][lb_inds], coords[2][lb_inds],
                s=10, c=clrs[lb], label=label_names[lb])

    lgnd = ax.legend(fontsize=20)
    for lb in range(10):
        lgnd.legendHandles[lb]._sizes = [60]

    return fig, ax

'''
ax.set_xlabel('PC 1', loc='center')
ax.set_ylabel('PC 2')
ax.set_zlabel('PC 3')
'''

fig, ax = get_latent_image(coords, title=f'{mname} iter={iter} l={layer}')
fig.show()

from sklearn.metrics import silhouette_score as ssc
from sklearn.metrics import calinski_harabasz_score as ch_score
from sklearn.metrics import davies_bouldin_score as db_score

ssc(coords.T, labels)

ch_score(coords.T, labels)

db_score(coords.T, labels)

"""#Multiple computations"""

import gc

part = 'test'
#iter = 100
#tlayer = 'layer4.0.sn1'
ds=1

all_metrics = np.zeros((len(ITERS), len(LAYERS), 3))

for i, iter in enumerate(ITERS[6:12]):
    print(iter)
    for j, tlayer in tqdm.tqdm(enumerate(LAYERS[:])):
        net_act = get_act_data(iter, part, tlayer)
        data = net_act.mean(axis=0).T
        #data += np.random.normal(size = data.shape)*1e-9
        D = MVData(data[:,:], rescale_rows=True, downsampling=ds)

        emb = D.get_embedding(embedding_params, g_params=graph_params, m_params=metric_params)
        coords = emb.coords

        all_metrics[i,j,0] = ssc(coords.T, labels)
        all_metrics[i,j,1] = ch_score(coords.T, labels)
        all_metrics[i,j,2] = db_score(coords.T, labels)

        fig, ax = get_latent_image(coords, title=f'{mname} iter={iter} l={tlayer}')
        impath = '/gdrive/MyDrive/iNeuroLab/MANGO (neurotrain)/Images'
        imname = f'iter={iter} l={tlayer} part={part}.png'
        plt.savefig(join(impath, imname))
        plt.close()
        gc.collect()

metrics_name = os.path.join('/gdrive/MyDrive/iNeuroLab/MANGO (neurotrain)', 'UMAP cl_metrics2.npz')
np.savez(metrics_name, all_metrics)

metrics1 = np.load(join('/gdrive/MyDrive/iNeuroLab/MANGO (neurotrain)', 'cl_metrics1.npz'))['arr_0']
metrics2 = np.load(join('/gdrive/MyDrive/iNeuroLab/MANGO (neurotrain)', 'cl_metrics2.npz'))['arr_0']

metrics = metrics1.copy()
metrics[9:18,:,:] = metrics2[:9].copy()

metric_names = ['Silhouette coefficient', 'CH score', 'DB score']
fig, axs = plt.subplots(1,3,figsize = (20,8))
fig.set_tight_layout(True)

for m, ax in enumerate(axs):
    ax = make_beautiful(ax)
    cmap = plt.get_cmap('plasma')
    clrs = cmap(np.linspace(0, 1.0, len(LAYERS)))

    for i in range(len(LAYERS)):
        clr = 1.0*i/len(LAYERS)
        ax.plot(np.log10(np.array(ITERS[:-2])+1), metrics[:-2,i,m],
                c=clrs[i], lw=3, label=LAYERS[i] if i%4==0 else None)

    ax.set_xlabel(r'$log_{10}(iter)$')
    ax.set_ylabel(metric_names[m])
    ax.legend()

import PIL
from PIL import Image

impath = '/gdrive/MyDrive/iNeuroLab/MANGO (neurotrain)/Images'

fig, axs = plt.subplots(1, 4, figsize = (20,8))
fig.set_tight_layout(True)

tlayer = 'layer4.1.sn2'
part='test'

for i, iter in enumerate([0,30,80,500]):
    imname = f'iter={iter} l={tlayer} part={part}.png'
    with Image.open(join(impath, imname)) as im:
        imarr = np.asarray(im)
        axs[i].imshow(imarr)
        axs[i].set_axis_off()

imname = f'_{tlayer}_dynamics.png'
plt.savefig(join(impath, imname))