# -*- coding: utf-8 -*-
"""Neurotrain analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wqRHiIBpi94ZK5jZQRBeSQb-Tkhc9XjX

# Initiation
"""

!pip install scipy --upgrade --quiet
!pip install GitPython --quiet
!pip install wget --quiet
!pip install pyyaml --quiet
!pip install pywavelets --quiet

import shutil
import importlib
import git
import sys
import json
import yaml
import pandas as pd
import seaborn as sns

import os
import tqdm
import hashlib
import copy

from itertools import combinations
import numpy as np

from functools import partialmethod
import matplotlib.pyplot as plt
import pickle
import warnings
import pandas as pd
from os.path import join

def clone_repo(repo, path_to_clone=None):
    rp = git.Repo.clone_from(f'https://github.com/iabs-neuro/{repo}',
                                branch='main',
                                to_path=path_to_clone
        )


def reload_module(name, exmodule, absname=None):
    print(f'module "{name}" is already imported, reloading...')
    exmodpath = exmodule.__path__[0]
    shutil.rmtree(exmodpath)
    print(f'Cloning module "{name}" to {exmodpath}...')
    clone_repo(name.split('.')[-1], path_to_clone=exmodpath)
    importlib.reload(exmodule)
    print(f'module "{name}" is successfully reloaded')


def import_external_repositories(repolist, extpath='/content', reload_internal=False):
    os.makedirs(extpath, exist_ok=True)

    for repo in repolist:
        rppath = os.path.join(extpath, repo)

        if repo in sys.modules:
            exmodule = sys.modules[repo]
            reload_module(repo, exmodule)

            if reload_internal:
                for module_name in os.listdir(f'{repo}/externals'):
                    intmodname = f'{repo}.externals.{module_name}'
                    intmodule = sys.modules[intmodname]
                    reload_module(intmodname, intmodule)

        else:
            if repo in os.listdir(extpath):
                shutil.rmtree(join(extpath, repo))
            print(f'Cloning module "{repo}" to {extpath}...')
            clone_repo(repo, path_to_clone=rppath)
            importlib.import_module(repo, package=None)

IMPORT_REPOS = ['driada']
import_external_repositories(IMPORT_REPOS)

from driada.gdrive.download import download_part_of_folder
from driada.gdrive.upload import save_file_to_gdrive

from driada.utils.output import *
from driada.utils.plot import *
import seaborn as sns

from google.colab import drive
drive.mount('/gdrive')
#PATH = '/gdrive/MyDrive/iNeuroLab/MANGO (neurotrain)/gan_sn/SJ-SNN-T50'
PATH = '/gdrive/MyDrive/iNeuroLab/MANGO (neurotrain)/gan_sn/ResNet18'
'''
LAYERS = ['sn1', 'layer1.0.sn1', 'layer1.1.sn1', 'layer2.0.sn1', 'layer2.1.sn1',
'layer3.0.sn1', 'layer3.1.sn1', 'layer4.0.sn1', 'layer4.1.sn1']
'''
LAYERS = ['layer1.0', 'layer1.1', 'layer2.0', 'layer2.1',
'layer3.0', 'layer3.1', 'layer4.0', 'layer4.1']

GENS = ['gan_sn']#, 'vae_vq']
#METHODS = ['RS', 'NG', 'TT', 'TT-s', 'TT-b', 'TT-exp']
METHODS = ['TT', 'TT-s', 'TT-b', 'TT-exp']

"""#Analysis"""

dataname = 'cifar10'
model = 'sjsnn'
units = np.arange(64)

all_data = {gen: dict() for gen in GENS}

for gen in GENS:
    all_data[gen] = {layer: dict() for layer in LAYERS}

    for layer in tqdm.tqdm(LAYERS):
        all_data[gen][layer] = {unit: dict() for unit in units}

        folder = os.path.join(PATH, f'{model}-{dataname}-{gen}-{layer}_processed')
        imagefolder = join(folder, 'AM_images')
        datafolder = join(folder, 'dat')
        datafiles = os.listdir(datafolder)

        for unit in units:
            all_data[gen][layer][unit] = {method: dict() for method in METHODS}

            pdata = f'opt_info_u{unit}_{layer}.pkl'
            try:
                with open(join(datafolder, pdata), 'rb') as f:
                    data = pickle.load(f)
                    print(data)
                    for method in METHODS:
                        tvals, zvals, activations = data[method]
                        opt_info = {
                            'max_t': tvals[-1],
                            'max_z': zvals[-1],
                            'max_a': activations[-1]
                        }

                        all_data[gen][layer][unit][method] = opt_info

            except FileNotFoundError:
                pass

all_data

"""## image differences

"""

from scipy.linalg import norm

tgen = 'gan_sn'

def get_layer_imdists(tgen, tlayer):
    all_dists = np.zeros((3, len(units)))
    for unit in units:
        zlist = [all_data[tgen][tlayer][unit][method]['max_z'] for method in METHODS]
        dists = [norm(zlist[0] - zlist[1]), norm(zlist[0] - zlist[2]), norm(zlist[1] - zlist[2])]
        all_dists[:, unit] = dists

    return all_dists.flatten()


distvals1 = get_layer_imdists(tgen, 'sn1')
distvals2 = get_layer_imdists(tgen, 'layer4.1.sn2')
distvals3 = get_layer_imdists(tgen, 'layer2.0.sn2')

fig, ax = create_default_figure(8,6)
ax.set_xlabel('distance between images')
sns.histplot(distvals1, bins=20, color='b', shrink=0.8, ax=ax, kde=True, edgecolor="white", label='sn1')
sns.histplot(distvals2, bins=20, color='r', shrink=0.8, ax=ax, kde=True, edgecolor="white", label='layer4.1.sn2')
#sns.histplot(distvals3, bins=20, color='y', ax=ax, kde=True, label='layer2.0.sn2')

ax.legend()
'''
_ = plt.hist(distvals1, bins=20, color='b')
_ = plt.hist(distvals2, bins=20, color='r')
'''

"""## Activations"""

def get_layer_activations(tgen, tlayer):
    all_acts = np.zeros((3, len(units)))
    for unit in units:
        alist = [all_data[tgen][tlayer][unit][method]['max_a'] for method in METHODS]
        all_acts[:, unit] = alist

    return all_acts.flatten()

tgen = 'gan_sn'

net_acts = []
for layer in LAYERS[:-1]:
    net_acts.append(get_layer_activations(tgen, layer))

fig, ax = create_default_figure(8,6)

sns.barplot(data=net_acts, errorbar=('sd', 1), width=0.7)
ax.set_ylabel('Normalized activation')
ax.set_xticklabels(LAYERS[:-1])
plt.xticks(rotation=90, fontsize=16)

ax.set_title(tgen)
#ax.legend()

"""# MANGO"""

!pip install numpy==1.24.0

!pip install GitPython
!pip install wget
!pip install teneva
!pip install nevergrad
!pip install ttopt
!pip install protes
!pip install snntorch
!pip install spikingjelly

! python -m pip install -U setuptools pip

!pip install cupy -vvvv

import cupy

import torch

IMPORT_REPOS = ['mango']
import_external_repositories(IMPORT_REPOS)

from mango.manager import MangoManager

data = 'cifar10'
gen = 'gan_sn'
model = 'sjsnn'
tlayer = 'sn1'
task = 'am'
kind = 'unit'
root = f'{model}_result_{tlayer}'
opt_args = {
    'opt_budget': 12000,
    'am_methods': ['TT', 'TT-s', 'TT-b']
}


manager = MangoManager(data=data,
                        gen=gen,
                        model=model,
                        task=task,
                        kind=kind,
                        cls=None,
                        unit=0,
                        layer=tlayer,
                        opt_args=opt_args,
                        root=root)

"""## neuron manipulation"""

manager.data

z = manager.gen.ind_to_poi(latent)
x = manager.gen.run(z)

"""## inference on MEIs"""

from driada.utils.plot import *
import seaborn as sns
from scipy.stats import entropy

rel_perpl = {layer: [] for layer in LAYERS}

gen = 'gan_sn'
tlayer = 'layer4.1.sn2'
unit=55
meth = 'TT'

for tlayer in LAYERS:
    for unit in tqdm.tqdm(np.arange(64)):
        for meth in METHODS:
            latent = all_data[gen][tlayer][unit][meth]['max_z']
            z = manager.gen.ind_to_poi(latent)
            x = manager.gen.run(z)

            for i in range(100):
                res = manager.model.run(x)

                probs_fn = torch.nn.Softmax(dim=0)
                probs = probs_fn(res).cpu().numpy()

                H0 = 2**(entropy([0.1 for _ in range(10)]))
                H = 2**entropy(probs)

                rel_perpl[tlayer].append(H/H0)

rel_perpl['layer4.1.sn2']

H0 = 2**(entropy([0.1 for _ in range(10)]))
rel_ent = {layer: [] for layer in LAYERS}

for layer in LAYERS:
    rel_ent[layer] = [np.log2(rp*H0)/H0 for rp in rel_perpl[layer]]

with open('rel_ent.pkl', 'wb') as f:
    pickle.dump(rel_ent, f)

fig, ax = create_default_figure(8,6)
_ = ax.hist(rel_ent, bins=100, color='r', label = 'layer4.1.sn2', density=True, alpha=0.7)
_ = ax.hist(rel_ent, bins=100, color='y', label = 'layer4.1.sn2', density=True, alpha=0.7)
_ = ax.hist(ent1, bins=100, color='b', label = 'sn1', density=True, alpha=0.7)
ax.set_xlim(0,0.5)
ax.set_xlabel('normalized entropy')
ax.set_ylabel('density')
ax.legend()

fig, ax = create_default_figure(8,6)
_ = ax.hist(rel_ent['sn1'], bins=100, color='r', label = 'layer4.1.sn2', density=True, alpha=0.7)

fig, ax = create_default_figure(8,6)
ax.set_xlim(0, 0.5)
ys = rel_ent['sn1']

nbins=100

range = max(ys) - min(ys)
hist, bins = np.histogram(ys, bins=nbins, range=(min(ys), max(ys)))
xs = (bins[:-1] + bins[1:])/2

_ = ax.bar(xs, hist, width = range*0.8/nbins, color='y', alpha=0.8)

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure(figsize=(8,8))
ax = fig.add_subplot(111, projection='3d')
nbins = 100

nhist = len(LAYERS)-2

cmap = plt.get_cmap('plasma')
clrs = cmap(np.linspace(0, 1.0, nhist))
zvals = np.arange(nhist)

for i in np.arange(nhist):
    c = clrs[i]
    z = zvals[i]
    layer = LAYERS[i]

    ys = rel_ent[layer]
    drange = max(ys) - min(ys)

    hist, bins = np.histogram(ys, bins=nbins, density=True)
    xs = (bins[:-1] + bins[1:])/2

    ax.bar(xs, hist, zs=z, zdir='y', width = drange*0.8/nbins,
           color=c, ec=c, alpha=0.9, label=layer)

ax.set_xlabel('normalized entropy', fontsize=16)
ax.set_ylabel('spiking layer', fontsize=16)
ax.set_zlabel('density', fontsize=16)

ax.legend(fontsize=10)

ax.set_xlim(0,0.5)

ax.set_box_aspect(aspect=None, zoom=0.9)

plt.show()

plt.imshow(x.cpu().numpy().transpose((1,2,0)))

from scipy.stats import entropy

"""#MEI evolution"""

#ITERS = [0,5,10,20,30,40,50,60,70,80,90,100,125,150,175,200,225,250,275,300,400,500,600,700,800,900]
#ITERS = [0,5,10,20,30,40,50,60,70,80,90,100,150,200,250,300,400,500,600,700]
ITERS = [0,1,2,4,8,16,32,64,97]


ITERPATH = '/gdrive/MyDrive/iNeuroLab/MANGO (neurotrain)/gan_sn/ResNet18'
#METHODS = ['0_TT-exp', '1_TT-exp', '2_TT-exp']

from yaml import Loader

with open(join(ITERPATH, 'ResNet18 evolution data full 1.yaml')) as f:
    all_data = yaml.load(f, Loader=Loader)

all_data[97]['layer1.0'][10][METHODS[0]].keys()

from mango.manager import MangoManager

data = 'cifar10'
gen = 'gan_sn'
model = 'sjsnn'
tlayer = 'sn1'
task = 'am'
kind = 'unit'
root = f'{model}_result_{tlayer}'

model_path = join(PATH,
                  'Model snapshots',
                  'spiking_resnet18_b360_e1000_sgd_lr0.2_wd0.0_ls0.1_ma0.2_ca1.0_sbn0_ra0_re0.1_aaugta_wide_size32_232_224_seed2020_T20',
                  'checkpoint_0.pth')

opt_args = {
    'opt_budget': 12000,
    'am_methods': ['TT', 'TT-s', 'TT-b']
}


manager = MangoManager(data=data,
                       gen=gen,
                       model=model,
                       task=task,
                       kind=kind,
                       cls=None,
                       unit=0,
                       layer=tlayer,
                       opt_args=opt_args,
                       root=root,
                       model_path=model_path)

nrand = 100
for iter in tqdm.tqdm(ITERS, position=0):
    for tlayer in LAYERS:
        for unit in tqdm.tqdm(np.arange(64)):
            for meth in METHODS:
                latent = all_data[iter][tlayer][unit][meth]['max_z']
                z = manager.gen.ind_to_poi(latent)
                x = manager.gen.run(z)

                all_probs = np.zeros((nrand, 10))
                rel_perpl = np.zeros(nrand)
                for i in range(nrand):
                    res = manager.model.run(x)

                    probs_fn = torch.nn.Softmax(dim=0)
                    probs = probs_fn(res).cpu().numpy()

                    all_probs[i, :] = probs
                    H0 = 2**(entropy([0.1 for _ in range(10)]))
                    H = 2**entropy(probs)

                    rel_perpl[i] = H/H0

                all_data[iter][tlayer][unit][meth]['probs'] = np.mean(all_probs, axis=0)
                all_data[iter][tlayer][unit][meth]['rel_perpl'] = np.mean(rel_perpl)

max_a_method = {meth: [] for meth in METHODS}
max_t_method = {meth: [] for meth in METHODS}

for iter in tqdm.tqdm(ITERS, position=0):
    for tlayer in LAYERS:
        for unit in np.arange(64):
            for meth in METHODS:
                opt_data = all_data[iter][tlayer][unit][meth]
                max_a_method[meth].append(float(opt_data['max_a']))
                max_t_method[meth].append(opt_data['max_t'])

"""#MEI evolution from .yaml

"""

import torchvision
import torch

variance_params = {
                'norm_m': [0.4914, 0.4822, 0.4465],
                'norm_v': [0.2471, 0.2435, 0.2616]
}

tr_norm_inv = torchvision.transforms.Compose(
    [
        torchvision.transforms.Normalize([0., 0., 0.], 1./np.array(variance_params['norm_v']),
                torchvision.transforms.Normalize(-np.array(variance_params['norm_m']), [1., 1., 1.])),
        ]
    )

def x_to_image(x):
    xt = torch.tensor(x)
    res = tr_norm_inv(xt).detach().squeeze().numpy()
    if len(res.shape) == 3:
        res = res.transpose(1, 2, 0)
        res = np.clip(res, 0, 1) if np.mean(res) < 2 else np.clip(res, 0, 255)
    #res = np.uint8(np.moveaxis(res.detach().squeeze().numpy(), 0, 2) * 256)
    return res

labels = {
            0: 'airplane',
            1: 'automobile',
            2: 'bird',
            3: 'cat',
            4: 'deer',
            5: 'dog',
            6: 'frog',
            7: 'horse',
            8: 'ship',
            9: 'truck',
        }

layer = 'layer1.0'
unit = 47

sel_inds = [1, 3, 7]
selected_iters = np.array(ITERS)[np.array([_ in sel_inds for _ in range(len(ITERS))])]
niters=len(selected_iters)

fig, axs = plt.subplots(niters, 4, figsize = (12, 4*niters))
for i, iter in enumerate(selected_iters):
    for j, method in enumerate(METHODS):
        x = all_data[iter][layer][unit][method]['max_image']

        #imdata = x_to_image(x)
        imdata = x
        imdata = imdata/np.max(imdata) # increase brightness without color change

        a = all_data[iter][layer][unit][method]['max_a']
        probs = all_data[iter][layer][unit][method]['probs']
        perp = all_data[iter][layer][unit][method]['rel_perpl']
        mclass = labels[np.argmax(probs)]

        ax = axs[i,j]
        ax.imshow(imdata)
        #ax.set_title(f'rperp={np.round(perp, 2)}, maxp={np.round(max(probs),2)}, class={mclass}, a={int(a*100)}%', fontsize=8)
        ax.set_title(f'class "{mclass}", p={int(max(probs)*100)}%, a={int(a*100)}%', fontsize=12)

plt.tight_layout()

"""## Proportion of selective"""

iters_to_check = ITERS[:15]

spec_count = np.zeros((len(LAYERS), len(iters_to_check)))
for i, layer in enumerate(LAYERS):
    for j, iter in enumerate(iters_to_check):
        is_spec = np.zeros((4,64))
        for k, unit in enumerate(range(64)):
            for l, meth in enumerate(METHODS):
                is_spec[l,k] = all_data[iter][layer][unit][meth]['max_a'] > 2

        spec_count[i,j] = np.mean(is_spec)*100

fig, ax = create_default_figure(12,6)
cax = ax.matshow(spec_count, cmap='plasma')
fig.colorbar(cax, ax=ax, label='% of selective neurons')

ax.set_yticklabels([None] + LAYERS)
ax.set_xticklabels([0] + iters_to_check[:])

iters_to_check = ITERS[:]

spec_count = np.zeros((len(LAYERS), len(iters_to_check)))
for i, layer in enumerate(LAYERS):
    for j, iter in enumerate(iters_to_check):
        is_spec = np.zeros((3,64))
        for k, unit in enumerate(range(64)):
            mclasses = []
            for l, meth in enumerate(METHODS[:-1]):
                #print(all_data[iter][layer][unit][meth])
                a = all_data[iter][layer][unit][meth]['max_a']
                probs = all_data[iter][layer][unit][meth]['probs']
                mclass = labels[np.argmax(probs)]
                mclasses.append(mclass)
                is_spec[l,k] = (max(probs) > 0.22) and a > 0

            if len(set(mclasses)) != 1: # check for different max classes from 3 methods
                is_spec[:,k] = 0

        spec_count[i,j] = np.mean(is_spec)*100

fig, ax = create_default_figure(12,6)
cax = ax.matshow(spec_count, cmap='plasma')
fig.colorbar(cax, ax=ax, label='% of selective neurons')

ax.set_yticklabels([None] + LAYERS)
ax.set_xticklabels([0] + iters_to_check[:])

"""## Accuracy & loss correlation"""

train_acc = np.load(join(ITERPATH, 'SJ-SNN T50 train acc.npz'))['arr_0']
train_loss = np.load(join(ITERPATH, 'SJ-SNN T50 train loss.npz'))['arr_0']
test_acc = np.load(join(ITERPATH, 'SJ-SNN T50 test acc.npz'))['arr_0']
test_loss = np.load(join(ITERPATH, 'SJ-SNN T50 test loss.npz'))['arr_0']

train_acc_std = np.load(join(ITERPATH, 'SJ-SNN T50 train acc std.npz'))['arr_0']
train_loss_std = np.load(join(ITERPATH, 'SJ-SNN T50 train loss std.npz'))['arr_0']
test_acc_std = np.load(join(ITERPATH, 'SJ-SNN T50 test acc std.npz'))['arr_0']
test_loss_std = np.load(join(ITERPATH, 'SJ-SNN T50 test loss std.npz'))['arr_0']

fig, axs = plt.subplots(1, 2, figsize=(20,10))
xdata = ITERS[:-6] #np.log2([_ + 1 for _ in ITERS])
nbatches1 = 50000/250
nbatches2 = 10000/250

ax = axs[0]
ax = make_beautiful(ax)

ax.plot(xdata, train_acc[:len(xdata)], c='b', linewidth=4, label='train acc.')
ax.plot(xdata, test_acc[:len(xdata)], c='r', linewidth=4, label='test acc.')
ax.fill_between(xdata,
                train_acc[:len(xdata)] - 3*train_acc_std[:len(xdata)]/np.sqrt(nbatches1),
                train_acc[:len(xdata)] + 3*train_acc_std[:len(xdata)]/np.sqrt(nbatches1),
                color='b', alpha=0.7)

ax.fill_between(xdata,
                test_acc[:len(xdata)] - 3*test_acc_std[:len(xdata)]/np.sqrt(nbatches1),
                test_acc[:len(xdata)] + 3*test_acc_std[:len(xdata)]/np.sqrt(nbatches1),
                color='r', alpha=0.5)


ax = axs[1]
ax = make_beautiful(ax)

ax.plot(xdata, train_loss[:len(xdata)], c='b', linewidth=4)
ax.plot(xdata, test_loss[:len(xdata)], c='r', linewidth=4)

iters_to_check = ITERS[:]
units = np.arange(64)

max_acts = np.zeros((len(LAYERS), len(iters_to_check), len(units)))
for i, layer in enumerate(LAYERS):
    for j, iter in enumerate(iters_to_check):
        for k, unit in enumerate(units):
            ma = []
            for l, meth in enumerate(METHODS):
                a = all_data[iter][layer][unit][meth]['max_a']
                ma.append(a)
            max_acts[i, j, k] = np.mean(ma)

fig, ax = plt.subplots(figsize = (10,8))
ax = make_beautiful(ax)

#cmap = plt.get_cmap('plasma')
clrs = ['r', 'g', 'b', 'c', 'violet', 'y', 'gold', 'purple', 'brown']

xdata = np.array(iters_to_check)
for i, layer in enumerate(LAYERS[:], start=4):
    #clr = cmap(1.0*i/len(LAYERS))
    bad_mei_neurons = np.where(max_acts[i, :, :] == 0)[1]
    good_mei_neurons = np.array([u for u in units if u not in bad_mei_neurons])

    madata = max_acts[i, :, good_mei_neurons]
    pldata = np.mean(madata, axis=0)
    pldata_err = np.std(madata, axis=0)/np.sqrt(len(good_mei_neurons))
    pldata_upper = pldata + 1*pldata_err
    pldata_lower = pldata - 1*pldata_err

    ax.fill_between(xdata, pldata_lower, y2=pldata_upper,
                    color=clrs[i], alpha=0.5, label=layer)

    ax.plot(xdata, pldata, c=clrs[i], linewidth=3)

xdata = ITERS[:-8] #np.log2([_ + 1 for _ in ITERS])

ax.plot(xdata, train_acc[:len(xdata)]/100.0, c='b', linewidth=4, label='train acc.')
ax.plot(xdata, test_acc[:len(xdata)]/100.0, c='r', linewidth=4, label='test acc.')

ax.fill_between(xdata,
                (train_acc[:len(xdata)] - 3*train_acc_std[:len(xdata)]/np.sqrt(nbatches1))/100.0,
                (train_acc[:len(xdata)] + 3*train_acc_std[:len(xdata)]/np.sqrt(nbatches1))/100.0,
                color='b', alpha=0.5)

ax.fill_between(xdata,
                (test_acc[:len(xdata)] - 3*test_acc_std[:len(xdata)]/np.sqrt(nbatches2))/100.0,
                (test_acc[:len(xdata)] + 3*test_acc_std[:len(xdata)]/np.sqrt(nbatches2))/100.0,
                color='r', alpha=0.5)

ax.legend(loc='lower right', fontsize=15)
ax.set_xlabel(r'$log_2$(epoch)')
ax.set_ylabel('MEI act. / model acc.')

"""## first time spec"""

iters_to_check = ITERS[:]

first_spec = -np.ones((len(LAYERS), len(units)))
for i, layer in enumerate(LAYERS):
    for j, iter in enumerate(iters_to_check):
        is_spec = np.zeros((3,64))
        for k, unit in enumerate(units):
            mclasses = []
            for l, meth in enumerate(METHODS):
                a = all_data[iter][layer][unit][meth]['max_a']
                probs = all_data[iter][layer][unit][meth]['probs']
                mclass = labels[np.argmax(probs)]
                mclasses.append(mclass)
                is_spec[l,k] = a > 0.75 #and (max(probs) > 0.8)

            if len(set(mclasses)) != 1: # check for different max classes from 3 methods
                is_spec[:,k] = 0

            if np.mean(is_spec[:,k]) == 1 and first_spec[i,k] == -1:
                first_spec[i,k] = iter + 1

fig, ax = create_default_figure(12,6)
cax = ax.matshow(first_spec, cmap='plasma')

ax.set_yticklabels([None] + LAYERS)
ax.set_xticklabels(units)

import seaborn as sns

clrs = ['r', 'g', 'b', 'c', 'violet', 'y', 'gold', 'purple', 'brown']

fig, ax = plt.subplots(figsize = (10,8))
ax = make_beautiful(ax)
df = pd.DataFrame(np.log2(first_spec.T))

sns.violinplot(df, cut=0, ax=ax, bw_adjust=0.8, palette=clrs, alpha=0.8)#, inner="quart")
ax.set_ylabel(r'$log_2$(epoch)')
ax.set_xticklabels(LAYERS[:])
plt.xticks(rotation=90, fontsize=18)

"""## activation history"""

iters_to_check = ITERS[:]
units = np.arange(64)

max_acts = np.zeros((len(LAYERS), len(iters_to_check), len(units)))
for i, layer in enumerate(LAYERS):
    for j, iter in enumerate(iters_to_check):
        for k, unit in enumerate(units):
            ma = []
            for l, meth in enumerate(METHODS):
                a = all_data[iter][layer][unit][meth]['max_a']
                ma.append(a)
            max_acts[i, j, k] = np.mean(ma)

fig, ax = plt.subplots(figsize = (10,8))
ax = make_beautiful(ax)

#cmap = plt.get_cmap('plasma')
clrs = ['r', 'g', 'b', 'c', 'violet', 'y', 'gold', 'purple', 'brown']

xdata = np.log2(np.array(iters_to_check)+1)
for i, layer in enumerate(LAYERS[:]):
    #clr = cmap(1.0*i/len(LAYERS))
    bad_mei_neurons = np.where(max_acts[i, :, :] == 0)[1]
    good_mei_neurons = np.array([u for u in units if u not in bad_mei_neurons])

    madata = max_acts[i, :, good_mei_neurons]
    pldata = np.mean(madata, axis=0)
    pldata_err = np.std(madata, axis=0)/np.sqrt(len(good_mei_neurons))
    pldata_upper = pldata + 1*pldata_err
    pldata_lower = pldata - 1*pldata_err

    ax.fill_between(xdata, pldata_lower, y2=pldata_upper,
                    color=clrs[i], alpha=0.5, label=layer)

    ax.plot(xdata, pldata, c=clrs[i], linewidth=3)

ax.legend(loc='lower left', fontsize=15)
ax.set_xlabel(r'$log_2$(epoch)')
ax.set_ylabel('MEI activation')
ax.set_yscale('log')

fig, ax = create_default_figure(8,6)

iter_ind = -1
net_acts = []
for i, layer in enumerate(LAYERS[:]):
    bad_mei_neurons = np.where(max_acts[i, iter_ind, :] == 0)[0]
    good_mei_neurons = np.array([u for u in units if u not in bad_mei_neurons])
    madata = max_acts[i, iter_ind, good_mei_neurons]
    net_acts.append(madata)

sns.barplot(net_acts, errorbar=('ci', 95), width=0.7, palette=clrs, alpha=0.75)
ax.set_ylabel('Normalized activation')
ax.set_xticklabels(LAYERS[:])
plt.xticks(rotation=90, fontsize=16)

"""## Max time analysis"""

iters_to_check = ITERS[:]
units = np.arange(64)

max_acts = np.zeros((len(LAYERS), len(iters_to_check), len(units)))
max_times = np.zeros((len(LAYERS), len(iters_to_check), len(units)))

for i, layer in enumerate(LAYERS):
    for j, iter in enumerate(iters_to_check):
        for k, unit in enumerate(units):
            ma = [all_data[iter][layer][unit][meth]['max_a'] for meth in METHODS]
            mt = [all_data[iter][layer][unit][meth]['max_t'] for meth in METHODS]
            max_acts[i, j, k] = np.mean(ma)
            max_times[i, j, k] = np.mean(mt)

fig, ax = plt.subplots(figsize = (10,8))
ax = make_beautiful(ax)

#cmap = plt.get_cmap('plasma')
clrs = ['r', 'g', 'b', 'c', 'violet', 'y', 'gold', 'purple', 'brown']

xdata = np.log2(np.array(iters_to_check)+1)
for i, layer in enumerate(LAYERS[:]):
    #clr = cmap(1.0*i/len(LAYERS))
    bad_mei_neurons = np.where(max_acts[i, :, :] == 0)[1]
    good_mei_neurons = np.array([u for u in units if u not in bad_mei_neurons])

    mtdata = max_times[i, :, good_mei_neurons]
    pldata = np.mean(mtdata, axis=0)
    pldata_err = np.std(mtdata, axis=0)/np.sqrt(len(good_mei_neurons))
    pldata_upper = pldata + 1*pldata_err
    pldata_lower = pldata - 1*pldata_err

    ax.fill_between(xdata, pldata_lower, y2=pldata_upper,
                    color=clrs[i], alpha=0.5, label=layer)

    ax.plot(xdata, pldata, c=clrs[i], linewidth=3)

ax.legend(loc='lower right', fontsize=15)
ax.set_xlabel(r'$log_2$(epoch)')
ax.set_ylabel('time')

"""## complexity analysis"""

iters_to_check = ITERS[:]
units = np.arange(64)

max_compl = np.zeros((len(LAYERS), len(iters_to_check), len(units)))
max_compl2 = np.zeros((len(LAYERS), len(iters_to_check), len(units)))
max_acts = np.zeros((len(LAYERS), len(iters_to_check), len(units)))
for i, layer in enumerate(LAYERS):
    for j, iter in enumerate(iters_to_check):
        for k, unit in enumerate(units):
            ma = []
            mc = []
            mc2 = []
            for l, meth in enumerate(METHODS):
                max_im = all_data[iter][layer][unit][meth]['max_image']
                zipped = np.savez_compressed('zipped_max_im.npz', a=max_im)

                c = os.path.getsize('zipped_max_im.npz')
                c2 = all_data[iter][layer][unit][meth]['complexity']

                a = all_data[iter][layer][unit][meth]['max_a']
                mc.append(c)
                mc2.append(c2)
                ma.append(a)
            max_compl[i, j, k] = np.mean(mc)
            max_compl2[i, j, k] = np.mean(mc2)
            max_acts[i, j, k] = np.mean(ma)

max_im.dtype

fig, axs = plt.subplots(1, 2, figsize = (16,8))
fig.set_tight_layout(True)

ax = axs[0]
ax = make_beautiful(ax)

#cmap = plt.get_cmap('plasma')
clrs = ['r', 'g', 'b', 'c', 'violet', 'y', 'gold', 'purple', 'brown']

xdata = np.log2(np.array(iters_to_check)+1)
for i, layer in enumerate(LAYERS[::2]):
    #clr = cmap(1.0*i/len(LAYERS))
    bad_mei_neurons = np.where(max_acts[i, :, :] == 0)[1]
    good_mei_neurons = np.array([u for u in units if u not in bad_mei_neurons])

    mcdata = max_compl[i, :, good_mei_neurons]/32/32/32/3
    pldata = np.mean(mcdata, axis=0)
    pldata_err = np.std(mcdata, axis=0)/np.sqrt(len(good_mei_neurons))
    pldata_upper = pldata + 1*pldata_err
    pldata_lower = pldata - 1*pldata_err

    ax.fill_between(xdata, pldata_lower, y2=pldata_upper,
                    color=clrs[i], alpha=0.5, label=layer)

    ax.plot(xdata, pldata, c=clrs[i], linewidth=3)

ax.legend(loc='lower right', fontsize=15)
ax.set_xlabel(r'$log_2$(epoch)')
ax.set_ylabel('MEI compression (.zip)')



ax = axs[1]
ax = make_beautiful(ax)

xdata = np.log2(np.array(iters_to_check)+1)
for i, layer in enumerate(LAYERS[::2]):
    #clr = cmap(1.0*i/len(LAYERS))
    bad_mei_neurons = np.where(max_acts[i, :, :] == 0)[1]
    good_mei_neurons = np.array([u for u in units if u not in bad_mei_neurons])

    mcdata = max_compl2[i, :, good_mei_neurons]/32/32/8
    pldata = np.mean(mcdata, axis=0)
    pldata_err = np.std(mcdata, axis=0)/np.sqrt(len(good_mei_neurons))
    pldata_upper = pldata + 1*pldata_err
    pldata_lower = pldata - 1*pldata_err

    ax.fill_between(xdata, pldata_lower, y2=pldata_upper,
                    color=clrs[i], alpha=0.5, label=layer)

    ax.plot(xdata, pldata, c=clrs[i], linewidth=3)

ax.legend(loc='lower right', fontsize=15)
ax.set_xlabel(r'$log_2$(epoch)')
ax.set_ylabel('MEI compression (.jpeg)')

"""## MEI differences"""

from scipy.linalg import norm
from scipy.spatial.distance import cosine


iters_to_check = ITERS[:]
units = np.arange(64)

all_dists = np.zeros((len(LAYERS), len(iters_to_check), len(units)))
max_acts = np.zeros((len(LAYERS), len(iters_to_check), len(units)))
for i, layer in enumerate(LAYERS):
    for j, iter in enumerate(iters_to_check):
        for k, unit in enumerate(units):
            zlist = [all_data[iter][layer][unit][meth]['max_z'].astype(float) for meth in METHODS]
            #dists = [norm(zlist[0] - zlist[1]), norm(zlist[0] - zlist[2]), norm(zlist[1] - zlist[2])]
            dists = [cosine(zlist[0], zlist[1]), cosine(zlist[0], zlist[2]), cosine(zlist[1], zlist[2])]

            alist = [all_data[iter][layer][unit][meth]['max_a'] for meth in METHODS]
            all_dists[i, j, k] = np.mean(dists)
            max_acts[i, j, k] = np.mean(alist)

fig, ax = plt.subplots(figsize = (10,8))
ax = make_beautiful(ax)

#cmap = plt.get_cmap('plasma')
clrs = ['r', 'g', 'b', 'c', 'violet', 'y', 'gold', 'purple', 'brown']

xdata = np.log2(np.array(iters_to_check)+1)
for i, layer in enumerate(LAYERS[::2]):
    #clr = cmap(1.0*i/len(LAYERS))
    bad_mei_neurons = np.where(max_acts[i, :, :] == 0)[1]
    good_mei_neurons = np.array([u for u in units if u not in bad_mei_neurons])

    ddata = all_dists[i, :, good_mei_neurons]
    pldata = np.mean(ddata, axis=0)
    pldata_err = np.std(ddata, axis=0)/np.sqrt(len(good_mei_neurons))
    pldata_upper = pldata + 1*pldata_err
    pldata_lower = pldata - 1*pldata_err

    ax.fill_between(xdata, pldata_lower, y2=pldata_upper,
                    color=clrs[i], alpha=0.5, label=layer)

    ax.plot(xdata, pldata, c=clrs[i], linewidth=3)

ax.legend(loc='lower right', fontsize=15)
ax.set_xlabel(r'$log_2$(epoch)')
ax.set_ylabel('MEI activation')

import seaborn as sns

clrs = ['r', 'g', 'b', 'c', 'violet', 'y', 'gold', 'purple', 'brown']

iter_ind = -1

fig, axs = plt.subplots(1, 2, figsize = (16,8))
fig.set_tight_layout(True)

for i, iter_ind in enumerate([0,-1]):
    ax = axs[i]
    ax = make_beautiful(ax)

    bad_mei_neurons = np.where(max_acts[i, :, :] == 0)[1]
    good_mei_neurons = np.array([u for u in units if u not in bad_mei_neurons])

    df = pd.DataFrame(all_dists[:, iter_ind, good_mei_neurons].T)

    sns.violinplot(df, cut=0, ax=ax, bw_adjust=0.8, palette=clrs, alpha=0.8)#, inner="quart")
    ax.set_ylabel('MEI cosine distance')
    ax.set_xticklabels(LAYERS[:])
    ax.tick_params(axis='x', labelrotation=90)
    ax.set_title(f'epoch {ITERS[iter_ind]}')
    ax.set_ylim(0.1,0.35)

"""## Inference on MEIs"""

iters_to_check = ITERS[:]
units = np.arange(64)

all_perpl = np.zeros((len(LAYERS), len(iters_to_check), len(units)))
max_acts = np.zeros((len(LAYERS), len(iters_to_check), len(units)))
for i, layer in enumerate(LAYERS):
    for j, iter in enumerate(iters_to_check):
        for k, unit in enumerate(units):
            alist = [all_data[iter][layer][unit][meth]['max_a'] for meth in METHODS]
            perplist = [all_data[iter][layer][unit][meth]['rel_perpl'] for meth in METHODS]
            all_perpl[i, j, k] = np.mean(perplist)
            max_acts[i, j, k] = np.mean(alist)

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure(figsize=(8,8))
ax = fig.add_subplot(111, projection='3d')
nbins = 10

nhist = len(LAYERS)
iter_ind = -1

cmap = plt.get_cmap('plasma')
clrs = cmap(np.linspace(0, 1.0, nhist))
zvals = np.arange(nhist)

for i in np.arange(nhist):
    c = clrs[i]
    z = zvals[i]
    layer = LAYERS[i]

    bad_mei_neurons = np.where(max_acts[i, :, :] == 0)[1]
    good_mei_neurons = np.array([u for u in units if u not in bad_mei_neurons])

    ys = all_perpl[i, iter_ind, good_mei_neurons]
    drange = max(ys) - min(ys)
    #drange = 1.0

    hist, bins = np.histogram(ys, bins=nbins, density=True)
    xs = (bins[:-1] + bins[1:])/2

    ax.bar(xs, hist, zs=z, zdir='y', width = drange*0.8/nbins,
           color=c, ec=c, alpha=0.9, label=layer)

ax.set_xlabel('normalized entropy', fontsize=16)
ax.set_ylabel('spiking layer', fontsize=16)
ax.set_zlabel('density', fontsize=16)

ax.legend(fontsize=10)

ax.set_xlim(0,1.0)

ax.set_box_aspect(aspect=None, zoom=0.9)

ax.set_title(f'epoch {ITERS[iter_ind]}')
plt.show()

fig, ax = plt.subplots(figsize = (10,8))
ax = make_beautiful(ax)

iter_ind = 19

for i in np.arange(nhist):
    c = clrs[i]
    layer = LAYERS[i]

    bad_mei_neurons = np.where(max_acts[i, :, :] == 0)[1]
    good_mei_neurons = np.array([u for u in units if u not in bad_mei_neurons])

    xdata = all_perpl[i, iter_ind, good_mei_neurons]
    ydata = max_acts[i, iter_ind, good_mei_neurons]

    ax.scatter(xdata, ydata, label=layer, c=c)

"""##Multineurons"""

iters_to_check = ITERS[:]

spec_index = np.full((len(LAYERS), 64, len(iters_to_check)), fill_value=-1)
for i, layer in enumerate(LAYERS):
    for j, iter in enumerate(iters_to_check):
        for k, unit in enumerate(range(64)):
            mclasses = []
            for l, meth in enumerate(METHODS):
                a = all_data[iter][layer][unit][meth]['max_a']
                probs = all_data[iter][layer][unit][meth]['probs']
                is_spec = (max(probs) > 0.2) and a > 0.5
                mclass = labels[np.argmax(probs)]
                mclasses.append(mclass)

            if len(set(mclasses)) != 1: # check for different max classes from 3 methods
                is_spec = 0

            if is_spec:
                spec_index[i, k, j] = np.argmax(probs)

#fig, ax = create_default_figure(12,6)

intcount = []
intcount2 = []
speccount = []
nospeccount = []
for i, layer in enumerate(LAYERS):
    n_classes_in_life = np.array([len(set(spec_index[i][_]) - set([-1])) for _ in range(64)])
    spec = np.where(n_classes_in_life == 1)[0]
    no_spec = np.where(n_classes_in_life == 0)[0]
    interesting = np.where(n_classes_in_life == 2)[0]
    interesting2 = np.where(n_classes_in_life > 2)[0]
    print(layer, interesting2)
    nospeccount.append(100.0*len(no_spec)/64)
    intcount.append(100.0*len(interesting)/64)
    intcount2.append(100.0*len(interesting2)/64)
    speccount.append(100.0*len(spec)/64)

fig, ax = create_default_figure()
'''
ax.plot(np.arange(9), nospeccount, c='grey', linewidth=5, label='нет СК')
ax.plot(np.arange(9), speccount, c='b', linewidth=5 ,label='1 СК')
ax.plot(np.arange(9), intcount, c='r', linewidth=5, label='2 СК')
ax.plot(np.arange(9), intcount2, c='y', linewidth=5, label='> 2 СК')
'''

df = pd.DataFrame({'no selectivity': nospeccount,
                   '1 class': speccount,
                   '2 classes': intcount,
                   '>2 classes': intcount2}, index=None)

df.plot.bar(rot=0, ax=ax, color=['grey', 'b', 'g', 'r'])

ax.set_ylabel('% of neurons')
#ax.set_xlabel('SNN layer')
ax.set_xticklabels(LAYERS)
plt.xticks(rotation=90, fontsize=20)

ax.legend(fontsize=20)

df = pd.DataFrame({'speed': speed,
                   'lifespan': lifespan,
                   'height': height}, index=index)
ax = df.plot.bar(rot=0)

interesting

neur_class = [dict() for meth in METHODS]
layer = 'layer4.1.sn1'
unit=1
for iter in ITERS:
    pr = np.zeros((3, 10))
    for i, meth in enumerate(METHODS):
       pr[i,:] = all_data[iter][layer][unit][meth]['probs']
       neur_class[i][iter] = np.argmax(pr[i,:])
    #neur_class[iter] = labels[np.argmax(np.mean(pr, axis=0))]

fig, ax = create_default_figure(8,6)
cmap = plt.get_cmap('plasma')
clrs = cmap(np.linspace(0, 1.0, 3))
for i, meth in enumerate(METHODS):
    ax.plot(ITERS[3:-3], [neur_class[i][iter] for iter in ITERS][3:-3], c=clrs[i], linewidth=3, label=meth)

ax.set_ylim(-1, 11)
ax.yaxis.set_ticks(range(10))
ax.yaxis.set_ticklabels([labels[_] for _ in range(10)])
ax.legend()

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure(figsize=(8,8))
ax = fig.add_subplot(111, projection='3d')
nbins = 10

nhist = len(ITERS[:])-2

cmap = plt.get_cmap('plasma')
clrs = cmap(np.linspace(0, 1.0, nhist))
zvals = np.arange(nhist)

for i in np.arange(nhist):
    c = clrs[i]
    z = zvals[i]
    iter = ITERS[i]

    ys = neur_prob[iter]
    drange = max(ys) - min(ys)

    hist, bins = np.histogram(ys, bins=nbins, density=True)
    xs = (bins[:-1] + bins[1:])/2

    ax.bar(xs, hist, zs=z, zdir='y', width = drange*0.8/nbins,
           color=c, ec=c, alpha=0.9, label=f'iter {iter}')

ax.set_xlabel('class', fontsize=16)
ax.set_ylabel('iteration', fontsize=16)
ax.set_zlabel('density', fontsize=16)

ax.legend(fontsize=10)

ax.set_xlim(0,1)

ax.set_box_aspect(aspect=None, zoom=0.9)

plt.show()

"""# Public link test (failed)

"""

target_path = '/MANGO'
os.makedirs(target_path, exist_ok=True)
folder_link = 'https://drive.google.com/drive/folders/1v2M9QyxugD87eIBEpm3VIa90P7HY7t85?usp=sharing'
#folder_link_gan = 'https://drive.google.com/drive/folders/1FfEsu9-Th89fvkq6OuHQZ-uKdpfp1XSS?usp=sharing'
#folder_link_gan = 'https://drive.google.com/drive/folders/1OpV9RqpSmajLm9v7bhNyeoWNNrAW0SDd?usp=sharing'
folder_link_gan = 'https://drive.google.com/drive/folders/1J_ZNvuSWDdjZC240mVIsGWIv8RkeqKh1?usp=sharing'
#folder_link = 'https://drive.google.com/drive/folders/1zpmKJtwWN70uAogWP4y71Xl1rPp4qlZU?usp=sharing'
tlayer = 'sn1'

_ = download_part_of_folder(target_path,
                            folder_link_gan,
                            key='',
                            extensions=['.png'],
                            via_pydrive=False)

_

os.listdir(target_path)

"""# performance analysis"""

LAYERS = ['sn1', 'layer1.0.sn1', 'layer1.1.sn1', 'layer2.0.sn1', 'layer2.1.sn1',
'layer3.0.sn1', 'layer3.1.sn1', 'layer4.0.sn1', 'layer4.1.sn1']
METHODS = ['RS', 'NG', 'TT', 'TT-s', 'TT-b', 'TT-exp']

dataname = 'cifar10'
model = 'sjsnn'
gen='gan_sn'
units = np.arange(64)

PATH = '/gdrive/MyDrive/iNeuroLab/MANGO (neurotrain)/gan_sn/SJ-SNN-T50/SJ-SNN iter 700/opt_full'

perf_data = {layer: dict() for layer in LAYERS}

for layer in tqdm.tqdm(LAYERS[:]):
    perf_data[layer] = {unit: dict() for unit in units}

    folder = os.path.join(PATH, f'{model}-{dataname}-{gen}-{layer}_processed')
    datafolder = join(folder, 'dat')
    datafiles = os.listdir(datafolder)

    for unit in units:
        perf_data[layer][unit] = {method: dict() for method in METHODS}

        pdata = f'opt_info_u{unit}_{layer}.pkl'
        try:
            with open(join(datafolder, pdata), 'rb') as f:
                data = pickle.load(f)
                for method in METHODS:
                    tvals, mvals, zvals, activations = data[method]
                    if len(tvals) == 0:
                        opt_info = {
                            't': [],
                            'm': [],
                            'a': []
                        }
                    else:
                        opt_info = {
                            't': tvals,
                            'm': mvals,
                            'a': np.array([a for a in activations])
                        }

                    perf_data[layer][unit][method] = opt_info

        except FileNotFoundError:
            print(f'{pdata} not found')
            pass

"""## iterations"""

perf_data['sn1'][20]

xvals = [10, 100, 1000, 9000]
yvals = [1, 0.7, 0.4, 0.1]

plt.plot(xvals, yvals)

mcolors = ['k', 'm', 'b', 'r', 'g', 'c']

for layer in LAYERS[:]:
    fig, ax = plt.subplots(figsize = (6,6))
    ax = make_beautiful(ax)

    ax.set_xscale('log')
    ax.set_yscale('log')

    for u, unit_info in perf_data[layer].items():
        for i, m in enumerate(METHODS):
            try:
                xvals = perf_data[layer][u][m]['m']
                yvals = 1 - perf_data[layer][u][m]['a']
                ax.plot(xvals, yvals, c=mcolors[i])
            except:
                pass

    ax.legend()

bins = np.logspace(1, 4, 9)

mcolors = ['k', 'm', 'b', 'r', 'g', 'c']

#bins = np.logspace(1, 4, 9)
bins = np.logspace(2, 3.5, 9)
alldata = np.zeros((len(LAYERS), len(METHODS), len(units), len(bins)))

for i, layer in enumerate(LAYERS[:]):
    for j, m in enumerate(METHODS):
        for u, unit_info in perf_data[layer].items():
            try:
                xvals = perf_data[layer][u][m]['t']
                #print(xvals)
                #yvals = [1 - v for v in perf_data[layer][u][m]['a']]
                yvals = perf_data[layer][u][m]['a']
                xbins = np.round(np.log10(xvals)*2).astype(int)
                alldata[i, j, u, xbins] += yvals

            except:
                pass

avdata = np.zeros((len(LAYERS), len(METHODS), len(bins)))
errdata = np.zeros((len(LAYERS), len(METHODS), len(bins)))

for i, layer in enumerate(LAYERS[:]):
    for j, m in enumerate(METHODS):
        for k, bin in enumerate(bins):
            vals = [v for v in alldata[i,j,:,k] if v != 0]
            avdata[i,j,k] = np.mean(vals)
            errdata[i,j,k] = np.std(vals)/np.sqrt(len(vals))

mcolors = ['y', 'm', 'b', 'r', 'g']

for i, layer in enumerate(LAYERS[:]):
    fig, ax = plt.subplots(figsize = (6,6))
    ax = make_beautiful(ax)

    ax.set_xscale('log')
    ax.set_yscale('log')

    for j, m in enumerate(METHODS[:-1]):
        data_ = avdata[i,j,:]
        err = errdata[i,j,:]
        good_points = ~np.isnan(data_)
        #print(bins)
        #print(data_)
        xvals = bins[good_points]
        yvals = data_[good_points]
        yvals1 = data_[good_points] - err[good_points]
        yvals2 = data_[good_points] + err[good_points]
        ax.plot(xvals, yvals, c=mcolors[j], label=m, linewidth=3)
        ax.fill_between(xvals, yvals1, yvals2, alpha=0.5, color=mcolors[j])

    ax.set_xlabel('iterations')
    ax.set_ylabel('activation')
    ax.legend()

avdata2 = np.zeros((len(METHODS), len(bins)))
errdata2 = np.zeros((len(METHODS), len(bins)))

for j, m in enumerate(METHODS):
    for k, bin in enumerate(bins):
        nnz_inds = np.where(alldata[:,j,:,k] != 0)
        vals = [v for v in alldata[:,j,:,k][nnz_inds]]
        avdata2[j,k] = np.mean(vals)
        errdata2[j,k] = 2*np.std(vals)/np.sqrt(len(vals))

mcolors = ['y', 'm', 'b', 'r', 'g']

fig, ax = plt.subplots(figsize = (6,6), dpi=200)
ax = make_beautiful(ax)
fig.set_tight_layout(True)

ax.set_xscale('log')
#ax.set_yscale('log')

for j, m in enumerate(METHODS[:-1]):
    data_ = avdata2[j,:]
    err = errdata2[j,:]
    good_points = ~np.isnan(data_)
    #print(bins)
    #print(data_)
    xvals = bins[good_points]
    yvals = data_[good_points]
    yvals1 = data_[good_points] - err[good_points]
    yvals2 = data_[good_points] + err[good_points]
    ax.plot(xvals, yvals, c=mcolors[j], label=m, linewidth=3)
    ax.fill_between(xvals, yvals1, yvals2, alpha=0.5, color=mcolors[j])

ax.set_xlabel('iterations')
ax.set_ylabel('activation')
ax.legend()

fig.savefig('act-iter.svg', format='svg')

"""## time"""

all_times = {m:[] for m in METHODS}
all_times2 = {m:[] for m in METHODS}
all_times3 = {m:[] for m in METHODS}
all_acts = {m:[] for m in METHODS}
all_acts2 = {m:[] for m in METHODS}
all_acts3 = {m:[] for m in METHODS}

for layer in LAYERS[:]:
    for u, unit_info in perf_data[layer].items():
        for i, m in enumerate(METHODS):
            for u, data in perf_data[layer].items():
                if 't' in data[m]:
                    if len(data[m]['t'])>5:
                        all_times[m].append(data[m]['t'][-1])
                        all_acts[m].append(data[m]['a'][-1])

                        ind2 = np.where(np.array(data[m]['m']) <= 100)[0][-1]
                        try:
                            all_times2[m].append(data[m]['t'][ind2])
                        except:
                            pass
                        all_acts2[m].append(data[m]['a'][ind2])

                        ind3 = np.where(np.array(data[m]['m']) <= 1000)[0][-1]
                        try:
                            all_times3[m].append(data[m]['t'][ind3])
                        except:
                            pass
                        all_acts3[m].append(data[m]['a'][ind3])

for m in METHODS:
    print(m)
    print(f'act100: {np.mean(all_acts2[m])} +- {np.std(all_acts2[m])/np.sqrt(len(all_acts2[m]))}')
    print(f'act1000: {np.mean(all_acts3[m])} +- {np.std(all_acts3[m])/np.sqrt(len(all_acts3[m]))}')
    print(f'act: {np.mean(all_acts[m])} +- {np.std(all_acts[m])/np.sqrt(len(all_acts[m]))}')

    print(f'time100: {np.mean(all_times2[m])} +- {np.std(all_times2[m])/np.sqrt(len(all_times3[m]))}')
    print(f'time1000: {np.mean(all_times3[m])} +- {np.std(all_times3[m])/np.sqrt(len(all_times3[m]))}')
    print(f'time: {np.mean(all_times[m])} +- {np.std(all_times[m])/np.sqrt(len(all_times[m]))}')

"""latex text"""

for m in METHODS:
    a1 = np.mean(all_acts2[m])
    a1err = np.std(all_acts2[m])/np.sqrt(len(all_acts2[m]))

    a2 = np.mean(all_acts3[m])
    a2err = np.std(all_acts3[m])/np.sqrt(len(all_acts3[m]))

    a3 = np.mean(all_acts[m])
    a3err = np.std(all_acts[m])/np.sqrt(len(all_acts[m]))

    t1 = np.mean(all_times2[m])
    t1err = np.std(all_times2[m])/np.sqrt(len(all_times3[m]))

    t2 = np.mean(all_times3[m])
    t2err = np.std(all_times3[m])/np.sqrt(len(all_times3[m]))

    t3 = np.mean(all_times[m])
    t3err = np.std(all_times[m])/np.sqrt(len(all_times[m]))

    vals = [a1, a2, a3, t1, t2, t3]
    errs = [a1err, a2err, a3err, t1err, t2err, t3err]

    cvals = [str(np.round(v, 3)) for v in vals]
    cerrs = [str(np.round(e, 3)) for e in errs]

    txtparts = [f'& ${cvals[i]}\!\pm\!{cerrs[i]}$ ' for i in range(len(cvals))]

    txt = ''.join(txtparts)
    print(txt)